/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.CtrManterPessoa;
import dao.DaoGenerico;
import dao.DaoLogin;
import java.util.List;
import javax.swing.JOptionPane;
import model.Pessoa;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author ENGENHARIA02
 */
public class FrmLogin extends javax.swing.JFrame {
    CtrManterPessoa ctrManterPessoa;
    Pessoa pessoa;
    boolean Logado;

    public boolean getLogado() {
        return Logado;
    }

    public void setLogado(boolean Logado) {
        this.Logado = Logado;
    }
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        ctrManterPessoa = new CtrManterPessoa();
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtUsuario = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jBtnLogin = new javax.swing.JButton();
        jBtnCadastre = new javax.swing.JButton();
        jLabelCadastre = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jTxtSobrenome = new javax.swing.JTextField();
        jLabelSobrenome = new javax.swing.JLabel();
        jBtnCriar = new javax.swing.JButton();
        jTxtCUsuario = new javax.swing.JTextField();
        jLabelCUsuario = new javax.swing.JLabel();
        jLabelCSenha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordCSenha = new javax.swing.JPasswordField();
        jPasswordSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");

        jLabelUsuario.setText("Usuário");

        jLabelSenha.setText("Senha");

        jBtnLogin.setText("Entrar");
        jBtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLoginMouseClicked(evt);
            }
        });

        jBtnCadastre.setText("Confirmar");
        jBtnCadastre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCadastreMouseClicked(evt);
            }
        });

        jLabelCadastre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelCadastre.setText("Cadastre-se");

        jLabelNome.setText("Nome");

        jLabelSobrenome.setText("Sobrenome");

        jBtnCriar.setText("Criar Conta");
        jBtnCriar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCriarMouseClicked(evt);
            }
        });

        jLabelCUsuario.setText("Usuário");

        jLabelCSenha.setText("Senha");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Faça seu Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jLabelSenha)
                    .addComponent(jLabelUsuario)
                    .addComponent(jBtnCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jBtnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jPasswordSenha))
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelSobrenome)
                    .addComponent(jLabelCSenha)
                    .addComponent(jLabelCUsuario)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxtNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtSobrenome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtCUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtnCadastre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(jPasswordCSenha, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(306, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSobrenome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabelCUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPasswordCSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnCadastre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnLogin)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnCriar)))
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(299, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCriarMouseClicked
        System.out.println("LOG STATUS | Clicou no Botão Criar Conta!");
        showThings();
    }//GEN-LAST:event_jBtnCriarMouseClicked

    private void jBtnCadastreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCadastreMouseClicked
        pessoa = new Pessoa();
        pessoa.setNome(jTxtNome.getText());
        pessoa.setSobrenome(jTxtSobrenome.getText());
        pessoa.setUsuario(jTxtCUsuario.getText());
        pessoa.setSenha(jPasswordCSenha.getText());
        if (ctrManterPessoa.gravarPessoa(pessoa) == 1) {
            jTxtNome.setText("");
            jTxtSobrenome.setText("");
            jTxtUsuario.setText("");
            jPasswordSenha.setText("");
            jTxtCUsuario.setText("");
            jPasswordCSenha.setText("");  
            JOptionPane.showMessageDialog(null, "Usuário cadastrado!");
            hideThings();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário não cadastrado!");
        }
    }//GEN-LAST:event_jBtnCadastreMouseClicked

    private void jBtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLoginMouseClicked
        DaoLogin d = new DaoLogin();
       
        System.out.println("LOG STATUS | Enviando valores do TextField para o Método de Validação...");
        System.out.println("LOG STATUS | Usuário: " + jTxtUsuario.getText() + " Senha: " + jPasswordSenha.getText());
        if (d.validaLogin(jTxtUsuario.getText(), jPasswordSenha.getText()) == 1) {
            //Usuario Logado
            System.out.println("LOG STATUS | Usuário Logado!");
            JOptionPane.showMessageDialog(null, "Logado com sucesso");
            setLogado(true);
        } else {
            //Usuario não encontrado
            System.out.println("LOG STATUS | Usuário não encontrado!");
            JOptionPane.showMessageDialog(null, "Usuário e senha incorretos!");
            setLogado(false);
        }
    }//GEN-LAST:event_jBtnLoginMouseClicked

    
    public void hideThings() {
        jLabelCadastre.setVisible(false);
        jLabelNome.setVisible(false);
        jLabelSobrenome.setVisible(false);
        jLabelCUsuario.setVisible(false);
        jLabelCSenha.setVisible(false);
        jTxtNome.setVisible(false);
        jTxtSobrenome.setVisible(false);
        jTxtCUsuario.setVisible(false);
        jPasswordCSenha.setVisible(false);
        jBtnCadastre.setVisible(false);
    }
    
    public void showThings() {
        jLabelCadastre.setVisible(true);
        jLabelNome.setVisible(true);
        jLabelSobrenome.setVisible(true);
        jLabelCUsuario.setVisible(true);
        jLabelCSenha.setVisible(true);
        jTxtNome.setVisible(true);
        jTxtSobrenome.setVisible(true);
        jTxtCUsuario.setVisible(true);
        jPasswordCSenha.setVisible(true);
        jBtnCadastre.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCadastre;
    private javax.swing.JButton jBtnCriar;
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCSenha;
    private javax.swing.JLabel jLabelCUsuario;
    private javax.swing.JLabel jLabelCadastre;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSobrenome;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordCSenha;
    private javax.swing.JPasswordField jPasswordSenha;
    private javax.swing.JTextField jTxtCUsuario;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtSobrenome;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
